# Generated by Django 2.2.5 on 2020-05-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicomapp', '0001_initial'),
    ]

    operations = [
    ]
